CREATE TABLE STATES ( 
	STATE CHAR(2) CCSID 273 NOT NULL , 
	NAME CHAR(30) CCSID 273 NOT NULL , 
	CONSTRAINT state_primary_key PRIMARY KEY( STATE ) 
) RCDFMT STATESF; 
  
ALTER TABLE STATES 
	ADD CONSTRAINT state_name_unique 
	UNIQUE( NAME ) ; 
  
LABEL ON TABLE STATES 
	IS 'US States' ; 
